## **What is Attention?**

The **attention model** is a fundamental concept in modern deep learning, especially in areas like **natural language processing (NLP)** and **computer vision**. Let's break it down clearly.

Attention is a mechanism that allows a model to dynamically focus on relevant parts of the input when making a prediction, instead of treating all parts equally.

For example:

* When translating a sentence from English to French, the model shouldn't treat all words in the sentence as equally important at every translation step.
* Instead, it should "attend" to specific words that are most relevant at each point.

---

## **Core Idea**

Given an input sequence, the attention mechanism computes a weighted average of all elements, where the weights represent the importance or relevance of each element.

It’s like saying:

> “For this step, I care mostly about this part of the input, a little bit about that part, and not much about the rest.”

---

## **How Does It Work?**

At a high level, attention takes:

1. **Query (Q)** – what you are trying to match or focus on
2. **Key (K)** – what you are comparing against
3. **Value (V)** – the information you're trying to retrieve

### The steps:

1. **Compute similarity scores** between the query and all keys.
2. **Apply softmax** to turn those scores into probabilities (attention weights).
3. **Use the attention weights** to take a weighted sum of the values.

---

## **Mathematical Formulation (Scaled Dot-Product Attention)**

$$
\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V
$$

Where:

* $Q$ = Query matrix
* $K$ = Key matrix
* $V$ = Value matrix
* $d_k$ = dimensionality of the key

The division by $\sqrt{d_k}$ prevents the dot products from becoming too large, stabilizing training.

---

## **Types of Attention**

1. **Soft Attention** – differentiable, easy to train with gradient descent.
2. **Hard Attention** – selects parts of the input explicitly; more challenging to train.

---

## **Popular Variants**

1. **Self-Attention (or Intra-Attention)**
   The sequence attends to itself, allowing models to learn dependencies between all positions.

2. **Multi-Head Attention**
   Multiple attention mechanisms are run in parallel to capture different aspects of information.

3. **Transformer Architecture**
   Uses self-attention extensively in both encoder and decoder layers and has become the foundation of models like BERT, GPT, T5, etc.

---

## **Applications**

* **Machine Translation**
* **Text Summarization**
* **Speech Recognition**
* **Image Captioning**
* **Question Answering**
* **Recommendation Systems**

---

## **Advantages**

✔ Focuses on relevant information

✔ Handles long-range dependencies

✔ Parallelizable (especially in Transformers)

✔ Scales better than RNNs for large datasets

---

In [ ]:
import numpy as np

# Simple embeddings for 4 words (each vector is 4-dimensional for simplicity)
word_embeddings = {
    "I": np.array([1.0, 0.0, 0.0, 0.0]),
    "love": np.array([0.0, 1.0, 0.0, 0.0]),
    "machine": np.array([0.0, 0.0, 1.0, 0.0]),
    "learning": np.array([0.0, 0.0, 0.0, 1.0])
}

# Input sentence broken into words
sentence = ["I", "love", "machine", "learning"]

# Stack embeddings for all words
values = np.stack([word_embeddings[word] for word in sentence])  # Shape (4, 4)
keys = values.copy()  # Keys are the same as values here for simplicity

# Let's say the current word we're focusing on is "love"
query = word_embeddings["love"].reshape(1, -1)  # Shape (1, 4)


In [ ]:
# Dot product between query and all keys
scores = np.dot(query, keys.T)  # Shape (1, 4)


In [ ]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=-1, keepdims=True)

attention_weights = softmax(scores)  # Shape (1, 4)


In [ ]:
output = np.dot(attention_weights, values)  # Shape (1, 4)


In [ ]:
print("Sentence:", sentence)
print("Query (word 'love'):\n", query)
print("Keys (all words):\n", keys)
print("Scores:\n", scores)
print("Attention Weights:\n", attention_weights)
print("Weighted Output:\n", output)


Sentence: ['I', 'love', 'machine', 'learning']
Query (word 'love'):
 [[0. 1. 0. 0.]]
Keys (all words):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Scores:
 [[0. 1. 0. 0.]]
Attention Weights:
 [[0.1748777  0.47536689 0.1748777  0.1748777 ]]
Weighted Output:
 [[0.1748777  0.47536689 0.1748777  0.1748777 ]]
